### ISSUE TITLE
7z password protected

### ISSUE THREAD

**Issue by patatetom** [bugnano/archivefs#4]
hi,
I haven't tested the other supported formats, but `archivefs` doesn't work with the `7z` format if the archive is password-protected (filenames protected or not).
the behavior is the same whether the archive was generated under Windows or Linux.
regards, lacsaP.

**Comment by bugnano** [comment]
Given that `archivefs` is only a wrapper of `libarchive`, it only supports what libarchive supports.

It seems that libarchive does not support password-protected 7z files, so I suggest opening a bug report on `libarchive` instead.

**Comment by patatetom** [comment]
it's not clearly documented, but it seems that `libarchive` doesn't support protected 7z format archives...
https://github.com/libarchive/libarchive/issues/579#issuecomment-1080001978
https://github.com/libarchive/libarchive/issues/1443#issuecomment-790259887

for information, `archivefs` crashes when it processes such an archive.

regards, lascaP.

**Comment by Dingo64** [comment]
In my tests libarchive supports:
- ZIP encrypted files,
- can list files in RAR and 7Zip archives but only with non-encrypted filenames, cannot unpack
